# Generated by Django 3.2 on 2021-08-22 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rt', 'Rented'), ('on', 'Owned')], max_length=2)),
                ('total_floors', models.IntegerField()),
                ('total_floor_area', models.IntegerField()),
                ('height', models.FloatField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
        ),
    ]
