# Generated by Django 3.2 on 2021-08-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Industrial'), ('in', 'Commercial but using as industrial'), ('cm', 'Commercial'), ('cm', 'Residential but using as commercial'), ('rs', 'Residential')], max_length=2)),
            ],
        ),
    ]
